insert into History (historyID, bugID, dateCompleted, statusName, priorityName) values (1, 58, '3/18/2023', 'Completed', 'Semi Important');
insert into History (historyID, bugID, dateCompleted, statusName, priorityName) values (2, 14, '2/18/2024', 'Completed', 'Semi Important');
insert into History (historyID, bugID, dateCompleted, statusName, priorityName) values (3, 42, '2/28/2024', 'Completed', 'Important');
insert into History (historyID, bugID, dateCompleted, statusName, priorityName) values (4, 17, '12/7/2023', 'Completed', 'Important');
insert into History (historyID, bugID, dateCompleted, statusName, priorityName) values (5, 13, '1/14/2024', 'Completed', 'Important');
insert into History (historyID, bugID, dateCompleted, statusName, priorityName) values (6, 15, '11/5/2023', 'Completed', 'Urgent');
insert into History (historyID, bugID, dateCompleted, statusName, priorityName) values (7, 74, '8/18/2023', 'Completed', 'Not Important');
insert into History (historyID, bugID, dateCompleted, statusName, priorityName) values (8, 17, '9/30/2023', 'Completed', 'Semi Important');
insert into History (historyID, bugID, dateCompleted, statusName, priorityName) values (9, 58, '7/25/2023', 'Completed', 'Urgent');
insert into History (historyID, bugID, dateCompleted, statusName, priorityName) values (10, 50, '1/14/2024', 'Completed', 'Urgent');
insert into History (historyID, bugID, dateCompleted, statusName, priorityName) values (11, 55, '12/26/2023', 'Completed', 'Not Important');
insert into History (historyID, bugID, dateCompleted, statusName, priorityName) values (12, 84, '4/7/2023', 'Completed', 'Not Important');
insert into History (historyID, bugID, dateCompleted, statusName, priorityName) values (13, 28, '6/27/2023', 'Completed', 'Not Important');
insert into History (historyID, bugID, dateCompleted, statusName, priorityName) values (14, 75, '7/25/2023', 'Completed', 'Semi Important');
insert into History (historyID, bugID, dateCompleted, statusName, priorityName) values (15, 64, '10/5/2023', 'Completed', 'Semi Important');
insert into History (historyID, bugID, dateCompleted, statusName, priorityName) values (16, 61, '7/3/2023', 'Completed', 'Urgent');
insert into History (historyID, bugID, dateCompleted, statusName, priorityName) values (17, 39, '2/1/2024', 'Completed', 'Semi Important');
insert into History (historyID, bugID, dateCompleted, statusName, priorityName) values (18, 3, '2/19/2024', 'Completed', 'Important');
insert into History (historyID, bugID, dateCompleted, statusName, priorityName) values (19, 6, '9/5/2023', 'Completed', 'Important');
insert into History (historyID, bugID, dateCompleted, statusName, priorityName) values (20, 19, '2/18/2024', 'Completed', 'Urgent');
