insert into Project (projectID, projectName) values (1, 'Alpha');
insert into Project (projectID, projectName) values (2, 'Home Ing');
insert into Project (projectID, projectName) values (3, 'Transcof');
insert into Project (projectID, projectName) values (4, 'Domainer');
insert into Project (projectID, projectName) values (5, 'Otcom');
insert into Project (projectID, projectName) values (6, 'Viva');
insert into Project (projectID, projectName) values (7, 'Sonair');
insert into Project (projectID, projectName) values (8, 'Rando');
insert into Project (projectID, projectName) values (9, 'Bigtax');
insert into Project (projectID, projectName) values (10, 'Andalax');